#!/bin/sh

if [ -x /etc/init.d/i-love-luci-console ]; then
	/etc/init.d/i-love-luci-console enable >/dev/null 2>&1 || true
	/etc/init.d/i-love-luci-console restart >/dev/null 2>&1 || true
fi

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
/etc/init.d/rpcd reload >/dev/null 2>&1 || true

exit 0
