include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-i-love-luci
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

LUCI_TITLE:=I Love LuCI modern application shell
LUCI_DEPENDS:=+luci-base +rpcd-mod-ucode +ttyd
LUCI_PKGARCH:=all

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=3aa49ec6bfc910647fa1c5a013e48eef

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
