#!/bin/sh

uci -q get luci.themes.ILoveLuCI >/dev/null || {
	uci set luci.themes.ILoveLuCI=/luci-static/i-love-luci
}

uci -q get luci.iloveluci >/dev/null || {
	uci set luci.iloveluci=theme
}

for option in variant density font menu_variant; do
	if ! uci -q get luci.iloveluci.$option >/dev/null; then
		value="$(uci -q get luci.openwrt2026.$option)"
		[ -n "$value" ] && uci set luci.iloveluci.$option="$value"
	fi
done

uci -q get luci.iloveluci.font >/dev/null || uci set luci.iloveluci.font=galano
uci -q get luci.iloveluci.simplified_save >/dev/null || uci set luci.iloveluci.simplified_save=1

uci -q delete luci.themes.OpenWrt2026
uci -q delete luci.openwrt2026

current_mediaurlbase="$(uci -q get luci.main.mediaurlbase)"
if [ "$PKG_UPGRADE" != 1 ] || [ "$current_mediaurlbase" = "/luci-static/openwrt2026" ]; then
	uci set luci.main.mediaurlbase=/luci-static/i-love-luci
fi

uci commit luci

exit 0
